tnbs = [
    ('D001', ' Telekom Deutschland GmbH'),
    ('D003', 'Multiconnect GmbH'),
    ('D004', 'NetCologne GmbH'),
    ('D005', 'ZZ_Carrier_D005'),
    ('D007', 'ZZ_Carrier_D007'),
    ('D008', 'Verizon Deutschland GmbH'),
    ('D009', ' Vodafone GmbH'),
    ('D010', 'ZZ_Carrier_D010'),
    ('D011', '1&1 Versatel Deutschland GmbH'),
    ('D012', 'ZZ_Carrier_D012'),
    ('D013', 'EWE TEL GmbH'),
    ('D014', 'ZZ_Carrier_D014'),
    ('D015', 'Freenet AG'),
    ('D016', 'KielNET GmbH'),
    ('D017', 'Colt Technology Services GmbH'),
    ('D019', 'ZZ_Carrier_D019'),
    ('D020', 'dtms GmbH'),
    ('D022', 'Communication Services Tele2 GmbH '),
    ('D023', 'HeLi NET Telekommunikation GmbH & Co. KG'),
    ('D025', 'IN-telegence GmbH & Co. KG'),
    ('D027', 'Ventelo GmbH'),
    ('D031', 'ZZ_Carrier_D031'),
    ('D032', 'DOKOM GmbH'),
    ('D035', 'BITEL Gesellschaft fuer Telekommunikation mbH'),
    ('D037', 'WOBCOM GmbH'),
    ('D038', 'TNG Network Management GmbH'),
    ('D041', 'ZZ_Carrier_D041'),
    ('D043', 'ZZ_Carrier_D043'),
    ('D045', 'HLkomm Telekommunikations GmbH'),
    ('D046', 'envia TEL GmbH'),
    ('D047', '01051 Telecom GmbH'),
    ('D048', 'ZZ_Carrier_D048'),
    ('D050', 'htp GmbH'),
    ('D051', '01058 Telecom GmbH'),
    ('D052', 'M-net GmbH '),
    ('D054', 'NetAachen GmbH'),
    ('D056', 'ZZ_Carrier_D056'),
    ('D057', 'ZZ_Carrier_D057'),
    ('D059', 'ZZ_Carrier_D059'),
    ('D060', 'ZZ_Carrier_D060'),
    ('D061', 'ZZ_Carrier_D061'),
    ('D066', 'ZZ_Carrier_D066'),
    ('D069', 'ZZ_Carrier_D069'),
    ('D070', 'First Communication GmbH'),
    ('D071', 'Netcom Kassel GmbH'),
    ('D072', 'ENTEGA Medianet GmbH'),
    ('D075', 'Median Telecom GmbH'),
    ('D076', 'SD Telecom Telekommunikations GmbH'),
    ('D079', 'ZZ_Carrier_D079'),
    ('D080', 'ZZ_Carrier_D080'),
    ('D081', 'Daten- und Telekommunikations- GmbH Dessau'),
    ('D082', 'ZZ_Carrier_D082'),
    ('D083', 'R-KOM Regensburg'),
    ('D084', 'VSE Net GmbH'),
    ('D085', 'ZZ_Carrier_D085'),
    ('D086', 'Mega Satellitenfernsehen GmbH'),
    ('D089', 'Osnatel'),
    ('D092', 'ZZ_Carrier_D092'),
    ('D093', 'ZZ_Carrier_D093'),
    ('D097', 'multiConnect GmbH'),
    ('D098', 'Goetel GmbH'),
    ('D099', 'ZZ_Carrier_D099'),
    ('D101', 'wilhelm.tel GmbH'),
    ('D107', '3U Telecom GmbH'),
    ('D109', 'netkom (ehem. encoLine)'),
    ('D112', 'LeuCom Telekommunikationsgesellschaft mbH'),
    ('D113', 'inopla GmbH'),
    ('D114', 'Deutsche Telefon Standard GmbH'),
    ('D115', 'MDCC Magdeburg-City-Com GmbH'),
    ('D117', 'Gamma Communications GmbH'),
    ('D120', 'Vodafone West GmbH'),
    ('D123', 'q-beyond'),
    ('D127', 'ZZ_Carrier_D127'),
    ('D133', 'PfalzKom GmbH'),
    ('D137', 'plusnet GmbH'),
    ('D141', 'Acoreus'),
    ('D142', 'net.services GmbH & Co. KG ehem. MR.NET'),
    ('D143', 'First Telecom GmbH'),
    ('D144', 'sdt.net AG'),
    ('D146', 'netzquadrat GmbH'),
    ('D150', 'ZZ_Carrier_D150'),
    ('D153', 'LEONET GmbH'),
    ('D154', 'PLANinterNET GmbH'),
    ('D155', 'ZZ_Carrier_D155'),
    ('D163', 'dus.net GmbH'),
    ('D167', 'DNS:NET Internet Service GmbH'),
    ('D168', 'bn:t Blatzheim Networks Telecom GmbH'),
    ('D171', 'Toplink GmbH'),
    ('D174', 'T-Systems Business Services GmbH'),
    ('D178', 'MK Netzdienste GmbH'),
    ('D180', 'Outbox AG'),
    ('D189', 'purtel.com GmbH'),
    ('D191', ' Vodafone Deutschland GmbH'),
    ('D194', 'G-FIT GmbH & Co. KG'),
    ('D201', ' 1&1 Telecom GmbH'),
    ('D202', 'inexio Informationstechnologie und Telekommunikation GmbH'),
    ('D208', 'Orange Business Germany GmbH'),
    ('D214', 'ZZ_Carrier_D214'),
    ('D215', 'OVH GmbH'),
    ('D218', 'purpur networks GmbH'),
    ('D220', 'Voxbone SA'),
    ('D221', '010090 GmbH'),
    ('D222', 'telegra GmbH'),
    ('D223', '42com Telecommunication GmbH'),
    ('D226', 'Spider Telecom GmbH'),
    ('D228', 'ZZ_Carrier_D228'),
    ('D235', 'ZZ_Carrier_D235'),
    ('D236', 'Mega Access GmbH'),
    ('D241', 'ZZ_Carrier_D241'),
    ('D242', 'Alnitak GmbH'),
    ('D248', 'umbra networks GmbH'),
    ('D250', 'Teleflash GmbH'),
    ('D252', 'OpenNumbers GmbH'),
    ('D256', 'HNS UG'),
    ('D263', 'inexio Breitband GmbH'),
    ('D267', 'ZZ_Carrier_D267'),
    ('D268', 'ZZ_Carrier_D268'),
    ('D270', 'ZZ_Carrier_D270'),
    ('D271', 'ZZ_Carrier_D271'),
    ('D274', 'ZZ_Carrier_D274'),
    ('D280', 'Ilm-Provider UG'),
    ('D287', 'ZZ_Carrier_D287'),
    ('D288', 'epcan GmbH'),
    ('D291', 'STADTWERKE SCHWEDT'),
    ('D292', ' Placetel'),
    ('D296', 'ZZ_Carrier_D296'),
    ('D298', 'neon networks UG'),
    ('D308', 'PrimaCom Berlin GmbH'),
    ('D321', 'ZZ_Carrier_D321'),
    ('D323', 'ecotel communication ag'),
    ('D328', 'WOBCOM GmbH'),
    ('D333', 'Wittenberg-net GmbH'),
    ('D334', 'SUC Dacor'),
    ('D335', '3U Telecom GmbH'),
    ('D353', 'ZZ_Carrier_D353'),
    ('D358', 'matelso GmbH'),
    ('D360', 'MPA NET Gesellschaft fuer Telekommunikation mbH'),
    ('D369', 'TELE AG'),
    ('D371', 'SOCO Network Solutions GmbH'),
    ('D396', 'VoiceOn Telecom Services GmbH Zadarma'),
    ('D397', 'Pyur'),
    ('D398', 'WEMACOM Telekommunikation GmbH'),
    ('D402', 'symbox Gesellschaft fuer Medienversorgung mbH'),
    ('D403', 'BICS Belgacom International Carriers'),
    ('D404', 'tenios GmbH'),
    ('D411', 'questnet GmbH'),
    ('D415', 'Gemeindewerke Hohenwestedt GmbH'),
    ('D416', 'Philunet'),
    ('D417', '1N Telecom GmbH'),
    ('D418', 'STROTH Telcom GmbH'),
    ('D419', 'CompuNet Systems GmbH'),
    ('D420', 'Marco Bungalski GmbH'),
    ('D423', 'Deutsche Glasfaser Wholesale GmbH'),
    ('D426', 'NFON AG'),
    ('D430', 'autphone GmbH'),
    ('D431', 'AlphaCron Datensysteme'),
    ('D432', 'intersaar GmbH'),
    ('D433', 'Brandl Services GmbH'),
    ('D441', 'Stiegeler Internet Service GmbH &Co. KG'),
    ('D445', 'TeleData GmbH'),
    ('D446', 'KEVAG Telekom GmbH'),
    ('D448', 'Vereinigte Stadtwerke Media GmbH'),
    ('D451', 'Telnyx Ireland Ltd'),
    ('D453', 'DIDWW Ireland Limited'),
    ('D454', 'nordischnet (GVG Glasfaser GmbH)'),
    ('D458', 'Drillisch Online'),
    ('D553', 'UNICOPE Deutschland GmbH'),
    ('D554', 'Stadtwerke Einbeck'),
    ('D555', 'Truphone GmbH'),
    ('D660', 'overturn technologies GmbH'),
    ('D661', 'pascom GmbH & Co KG'),
    ('D662', 'Devenia Systems GmbH'),
    ('D663', 'Westconnect GmbH'),
    ('D664', 'GS WEBSERVICES'),
    ('D665', 'LEW GmbH'),
    ('D666', 'Stadtwerke Luebeck'),
    ('D667', 'TraveKom Telekommunikationsgesellschaft mbH'),
    ('D668', 'Leer'),
    ('D690', 'MagicButton'),
    ('D697', 'WTG communication'),
    ('D698', 'Gesellschaft fuer Digitale Werte mbH'),
    ('D699', 'Ostertag DeTeWe GmbH'),
    ('D700', 'Avacon Connect GmbH'),
    ('D701', 'CyQon'),
    ('D702', 'DMRZ Deutsches Mittelstandsrechenzentrum Betreibergesellschaft mbH'),
    ('D703', 'e.discom Telekommunikations GmbH'),
    ('D704', 'Troiline Jeti-Line'),
    ('D705', 'Skype'),
    ('D706', 'carpeNet GmbH'),
    ('D707', 'LKG Lausitzer Kabelbetriebsgesellschaft mbH'),
    ('D708', 'dd Handelsgesellschaft mbH'),
    ('D709', 'Jens Heilmann e.K'),
    ('D710', 'C. Knabber GmbH'),
    ('D711', 'ITK.COACH GmbH'),
    ('D712', 'Deutsche GigaNetz GmbH'),
    ('D713', 'Stern Kom GmbH'),
    ('D714', 'WEMAG AG'),
    ('D715', 'Stadtwerke Ahrensburg GmbH'),
    ('D716', 'Stadtwerke Neustadt'),
    ('D717', 'terralink networks GmbH'),
    ('D718', 'amisol GmbH - allgaeuDSL'),
    ('D719', 'Genias Internet '),
    ('D720', 'EDNT IT Services GmbH'),
    ('D721', 'SWT trilan GmbH'),
    ('D722', 'byon gmbh'),
    ('D723', 'imos Gesellschaft fuer Internet-Marketing und Online-Services mbH '),
    ('D724', 'Francotyp-Postalia Vertrieb und Service GmbH'),
    ('D725', 'Mietho & Baer'),
    ('D726', 'Innofactory GmbH'),
    ('D727', 'Freitaler Stadtwerke GmbH'),
    ('D728', 'IP Exchange'),
    ('D729', 'GlobalConnect GmbH'),
    ('D730', 'RSM Freilassing, Michael Reiner Rack'),
    ('D731', 'DEK Telecom GmbH'),
    ('D732', 'MAINGAU Energie GmbH'),
    ('D733', 'Vicidial Hosting Europe GmbH & Co KG'),
    ('D734', 'Stadtwerke Rendsburg GmbH'),
    ('D735', 'E.ON Energie Deutschland GmbH'),
    ('D736', 'Greenfiber Internet & Dienste GmbH'),
    ('D737', 'Globalways Managed Service GmbH'),
    ('D738', 'SWU Telenet GmbH'),
    ('D739', 'Stadtwerke Nuertingen'),
    ('D740', 'vitroconnect GmbH'),
    ('D741', 'ZEAG Energie AG'),
    ('D742', 'NU Informationssysteme GmbH'),
    ('D743', 'KNT Internet'),
    ('D744', 'Schleswiger Stadtwerke GmbH'),
    ('D745', 'Kumeno GmbH'),
    ('D746', 'ProCRM IT-Systems GmbH'),
    ('D747', 'XXX'),
    ('D748', 'ATL Antennentechnik Lubmin'),
    ('D749', 'DALASON GmbH'),
    ('D750', 'FNOH-DSL Suedheide GmbH'),
    ('D751', 'Funk und Technik GmbH Forst'),
    ('D752', 'MCN Telekommunikacios'),
    ('D753', 'acmeo GmbH'),
    ('D754', 'NetTask GmbH'),
    ('D755', 'Stadtwerke Nortorf Breitband GmbH'),
    ('D756', 'Freikom GmbH'),
    ('D757', 'itk communications GmbH'),
    ('D758', 'Stadtwerke Finsterwalde GmbH'),
    ('D759', 'neu-medianet GmbH'),
    ('D760', 'MEGA Monheimer Elektrizitaets- und Gasversorgung GmbH'),
    ('D761', 'RS Gesellschaft fuer Informationstechnik mbH & Co. KG'),
    ('D762', 'Stadtwerke Ruesselsheim'),
    ('D763', 'RFT kabel Brandenburg GmbH'),
    ('D764', 'PTC Telecom GmbH'),
    ('D765', 'MIXvoip GmbH'),
    ('D766', 'ITS AG'),
    ('D767', 'Dolphin IT-Systeme e.K.'),
    ('D768', 'Portunity GmbH'),
    ('D769', 'InSysCo Datensysteme GmbH'),
    ('D770', 'TeleForte AG'),
    ('D771', 'Stadtwerke Geesthacht GmbH'),
    ('D772', 'RST Datentechnik GmbHu.com GmbH & Co. KG'),
    ('D773', 'pinnau.com GmbH & Co. KG'),
    ('D774', 'Stadtwerke Goerlitz AG'),
    ('D775', 'Stadtwerke Itzehoe GmbH'),
    ('D776', 'gnTel GmbH'),
    ('D777', 'Philis Informationssystemtechnik'),
    ('D778', 'mobiz.tel'),
    ('D779', 'Business Phone Net GmbH & Co. KG'),
    ('D780', 'Stadtwerke Eutin GmbH'),
    ('D781', 'Stadtwerke Buehl GmbH'),
    ('D782', 'Snellstar GmbH'),
    ('D783', 'TeGe Deutschland GmbH'),
    ('D784', 'telba AG'),
    ('D785', 'Tele System GmbH Rostock'),
    ('D786', 'Grossgemeinschaftsantennenanlage "Oberes Sprottental"'),
    ('D787', 'Twilio Inc.'),
    ('D788', 'R&M SimplyTechnnologies GmbH'),
    ('D789', 'getSolve IT GmbH'),
    ('D790', 'Stadtwerke Hammelburg GmbH'),
    ('D791', 'Drahtlos-DSL GmbH Mittelsachsen'),
    ('D792', 'D&T Internet GmbH'),
    ('D793', 'telkodata GmbH'),
    ('D794', 'eins energie in sachsen GmbH & Co. KG'),
    ('D795', 'NGN Telecom GmbH'),
    ('D796', 'Filiago GmbH & Co. KG'),
    ('D797', 'CNT AG'),
    ('D798', 'Sycor GmbH'),
    ('D799', 'Streamworx'),
    ('D800', 'Herzo Media GmbH & Co. KG'),
    ('D801', 'next id GmbH'),
    ('D802', 'GWS Stadtwerke Hameln GmbH'),
    ('D803', 'Stadtwerke Bochum GmbH'),
    ('D804', 'TKN Deutschland GmbH'),
    ('D805', 'GGEW net GmbH'),
    ('D806', 'NETHINKS GmbH'),
    ('D807', 'EMOTEC NETWORKS GmbH'),
    ('D808', 'TWL-KOM GmbH'),
    ('D809', 'MDDSL GmbH'),
    ('D810', 'StarTech'),
    ('D811', 'ENSO Energie Sachsen Ost AG'),
    ('D812', 'WiSoTEL'),
    ('D813', 'USA Global Link GmbH'),
    ('D814', 'cyberways Informationsdienste GmbH'),
    ('D815', 'SipNow'),
    ('D816', 'Stadtwerke Langenfeld'),
    ('D817', 'Gustav Internet GmbH & Co. KG'),
    ('D818', 'GTT Interroute'),
    ('D819', 'A+ GmbH'),
    ('D820', 'XXX'),
    ('D821', 'Epcan GmbH'),
    ('D822', 'brain4kom AG'),
    ('D823', 'Rhoennet'),
    ('D824', 'gnTel GmbH'),
    ('D825', 'Stadtwerke Flensburg GmbH'),
    ('D826', 'ccn corporate communication networks GmbH'),
    ('D827', 'Breitbandservice Gantert GmbH & Co. KG'),
    ('D828', 'Q-DSL home GmbH'),
    ('D829', 'km3 teledienst GmbH'),
    ('D830', 'LWLcom GmbH'),
    ('D831', 'twumber UG'),
    ('D832', 'Comtalk'),
    ('D833', 'Stadtwerke Barmstedt Xtra GmbH'),
    ('D834', 'Osnatel'),
    ('D835', 'DSLmobil GmbH'),
    ('D836', 'WEBDISCOUNT GmbH & Co. KG'),
    ('D837', 'simple Communication GmbH'),
    ('D838', 'Teledata'),
    ('D839', 'Telekommunikation Lindau GmbH'),
    ('D840', 'primastrom GmbH	'),
    ('D841', 'Disquom Funktechnik GmbH'),
    ('D842', 'TV-Netzgesellschaft mbH Guben'),
    ('D843', 'Thuega SmartService GmbH'),
    ('D844', 'T-M-Net'),
    ('D845', 'EuraLink'),
    ('D846', 'K-net Telekommunikation GmbH'),
    ('D847', 'Stadtwerke Konstanz GmbH'),
    ('D848', 'Starface GmbH'),
    ('D849', 'SIPup'),
    ('D850', 'newone GmbH'),
    ('D851', 'GVG Glasfaser GmbH'),
    ('D852', 'willy.tel GmbH'),
    ('D853', 'foncloud GmbH & Co. KG'),
    ('D854', 'Sat Internet Services GmbH'),
    ('D855', 'GWHtel Gmbh & Co.KG'),
    ('D856', 'VOIP2GSM'),
    ('D857', 'net-and-phone GmbH'),
    ('D858', 'PFALZconnect GmbH'),
    ('D859', 'Elementmedia'),
    ('D860', 'Skytron'),
    ('D861', 'Ilm-Provider UG'),
    ('D862', 'CS Telecom'),
    ('D863', 'Regionalantenne'),
    ('D864', 'Web + Phone GmbH'),
    ('D865', 'Breitbandversorgung Rhein-Neckar'),
    ('D866', 'Q-MEX Networks'),
    ('D867', 'Bisping & Bisping GmbH & Co. KG'),
    ('D868', 'Stadtwerke Bad Reichenhall KU'),
    ('D869', 'Stadtwerke Dorfen GmbH'),
    ('D870', 'TELTA Citynetz GmbH'),
    ('D871', 'Rapidata GmbH'),
    ('D872', 'Moderne Kommunikationstechnologie Hohentengen GmbH'),
    ('D873', 'net services GmbH & Co KG	'),
    ('D874', 'tkrz Stadtwerke GmbH'),
    ('D875', 'Herznet - EWR AG'),
    ('D876', 'Photonium NetSolutions GmbH'),
    ('D877', 'Stadtnetz Bamberg'),
    ('D878', 'Arche Net'),
    ('D879', 'Telepark Passau GmbH'),
    ('D880', 'GELSEN-NET Kommunikationsgesellschaft mbH'),
    ('D881', 'innogy TelNet GmbH'),
    ('D882', 'Kadsoft Computer GmbH Freital	'),
    ('D883', 'TeamFON GmbH'),
    ('D884', 'ZZ_Carrier_D884'),
    ('D885', 'telego! GmbH'),
    ('D886', 'NeXXt Mobile GmbH '),
    ('D887', 'Getinternet GmbH'),
    ('D888', 'MUENET GmbH'),
    ('D889', 'Eusanet'),
    ('D890', 'Titan Networks GmbH'),
    ('D891', 'Kamikom'),
    ('D892', 'ENTEGA Medianet GmbH'),
    ('D893', 'JOBST DSL e.K.'),
    ('D894', 'comjoo business solutions GmbH'),
    ('D895', 'DegNet'),
    ('D896', 'SOCO Network Solutions GmbH'),
    ('D897', 'OFFICE-ED Computer GmbH'),
    ('D898', 'Versorgungsbetriebe Bordesholm GmbH'),
    ('D899', 'Mango Office GmbH'),
    ('D900', 'purtel.com GmbH'),
    ('D901', 'WiDSL OR Network GmbH'),
    ('D902', 'congstar GmbH'),
    ('D903', 'COS-on-Air OHG'),
    ('D904', 'DachauCityCom'),
    ('D905', ' easybell GmbH'),
    ('D906', 'TelemaxX Telekommunikation GmbH'),
    ('D907', 'sipload'),
    ('D908', 'mobilcom-debitel GmbH'),
    ('D909', 'Kabelfernsehen Muenchen ServiCenter GmbH & Co.KG'),
    ('D910', 'E-Plus Gruppe (Base)'),
    ('D911', 'rockenstein AG'),
    ('D912', 'sipkom'),
    ('D913', 'ZZ_Carrier_D913'),
    ('D914', 'COM-IN Telekommunikations GmbH'),
    ('D915', ' o2 GmbH'),
    ('D916', 'WiTCOM'),
    ('D917', 'SIPbase (reventix)'),
    ('D918', 'skyDSL Deutschland'),
    ('D919', 'E-Werk Goldbach-Hoesbach'),
    ('D920', 'SWB AG (eine Marke von EWE TEL)'),
    ('D921', 'FunknetzHG'),
    ('D922', 'KurpfalzTel mbH'),
    ('D923', 'smart-DSL GmbH	'),
    ('D924', 'Northern Access GmbH '),
    ('D925', '1click2 Internet Services GmbH'),
    ('D926', 'BORnet GmbH'),
    ('D927', 'WIRECLOUD'),
    ('D928', 'fonial'),
    ('D929', 'KEVAG Telekom GmbH'),
    ('D930', 'ACO Computerservice GmbH'),
    ('D931', 'Hofnetz und IT Services GmbH'),
    ('D932', 'globalnumbers'),
    ('D933', 'Flink Glasfaser'),
    ('D934', 'Brandl Services GmbH'),
    ('D935', 'hugo internet GmbH & Co. KG'),
    ('D936', 'komro GmbH'),
    ('D937', 'true global communications GmbH'),
    ('D938', 'optimaconnect GmbH'),
    ('D939', 'equada GmbH'),
    ('D940', 'Thueringer Netkom GmbH'),
    ('D941', 'intersaar GmbH'),
    ('D942', 'Comulus AG'),
    ('D943', 'planet 33 AG'),
    ('D944', 'teliko GmbH'),
    ('D945', 'EFN eifel-net'),
    ('D946', 'omnidat'),
    ('D947', 'RelAix Networks GmbH'),
    ('D948', 'mieX Deutschland GmbH'),
    ('D949', 'Pfalzcloud'),
    ('D950', 'COMplusnet'),
    ('D951', 'Stadtwerke Trostberg GmbH'),
    ('D952', 'pepcom GmbH'),
    ('D953', 'Buchholz Digital GmbH'),
    ('D954', 'SWN Stadtwerke Neumuenster'),
    ('D955', 'Ortenau DSL'),
    ('D956', 'Unitymedia Hessen GmbH & Co. KG'),
    ('D957', 'TEFONIX UG'),
    ('D958', 'Avaya GmbH & Co. KG'),
    ('D959', 'INCAS GmbH'),
    ('D960', 'sewinet'),
    ('D961', 'C&S Breitband GmbH'),
    ('D962', 'IP Telecom Bulgaria (Zadarma)'),
    ('D963', 'Inter.net Germany GmbH'),
    ('D964', 'TELCAT MULTICOM GmbH'),
    ('D965', 'Voys Deutschland'),
    ('D966', 'schnell-im-netz.de GmbH & Co.KG'),
    ('D967', 'TM Mittelstand'),
    ('D968', 'ZZ_Carrier_D968'),
    ('D969', 'DW-TelefonDienste'),
    ('D970', 'Hofmeier Media'),
    ('D971', 'NetCom BW GmbH'),
    ('D972', 'Deutsche Glasfaser Business GmbH'),
    ('D973', 'MaTelSo GmbH'),
    ('D974', 'vio:networks GmbH'),
    ('D975', 'ZZ_Carrier_D975'),
    ('D976', 'ip-fabric GmbH'),
    ('D977', 'HochrheinNET GmbH	'),
    ('D978', 'Stadtwerke Annaberg-Buchholz GmbH'),
    ('D979', 'NTTCable Service KG'),
    ('D980', 'zollernalb-data GmbH'),
    ('D981', 'vocatel business gmbh'),
    ('D982', 'NeckarCom'),
    ('D983', 'primacall GmbH'),
    ('D984', 'NEW Niederrhein Energie und Wasser GmbH'),
    ('D985', 'Stadtwerke Marburg GmbH'),
    ('D986', 'NYNEX satellite OHG'),
    ('D987', 'KomMITT-Ratingen GmbH'),
    ('D988', 'ansit-com GmbH'),
    ('D989', 'Peoplefone GmbH'),
    ('D990', 'Unser Ortsnetz GmbH'),
    ('D991', 'Telenec Telekommunikation Neustadt GmbH'),
    ('D992', 'TNG Stadtnetz GmbH'),
    ('D993', 'Enreach Communications GmbH'),
    ('D994', 'Teleport GmbH'),
    ('D995', 'Vereinigte Stadtwerke Media GmbH'),
    ('D996', 'echtschnell GmbH'),
    ('D997', 'ETN EmslandTel.Net GmbH & Co. KG'),
    ('D998', 'Orange Business Germany GmbH'),
    ('D999', 'GWS Stadtwerke Hameln GmbH'),
]